# Generated by Django 3.0.3 on 2020-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='bg_color',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
