# Generated by Django 3.0.3 on 2020-02-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_auto_20200217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='audio',
            field=models.FileField(upload_to='emotions/'),
        ),
    ]
